version: '3'

services:
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - servicesNetwork

networks:
  servicesNetwork:
    driver: bridge
    
volumes:
  mongo:
    driver: local
